name: Bug Report
description: Report incorrect, misleading, or broken guidance in Devil's Advocate
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report an issue. Please fill in the details below — the more specific you are, the faster we can fix it.

  - type: input
    id: affected-file
    attributes:
      label: Affected File
      description: Which file contains the incorrect content?
      placeholder: "frameworks/handbrake-protocol.md"
    validations:
      required: true

  - type: input
    id: line-number
    attributes:
      label: Line Number (approximate)
      description: What line number is the issue on?
      placeholder: "Line 142"
    validations:
      required: false

  - type: textarea
    id: current-content
    attributes:
      label: Current Content (what the file says)
      description: Paste the exact text that is incorrect.
      render: markdown
    validations:
      required: true

  - type: textarea
    id: issue-description
    attributes:
      label: What Is Wrong
      description: Explain why this content is incorrect, misleading, or broken. Include citations or evidence where possible.
    validations:
      required: true

  - type: textarea
    id: suggested-fix
    attributes:
      label: Suggested Fix
      description: What should the content say instead? Paste a corrected version if you have one.
      render: markdown
    validations:
      required: false

  - type: dropdown
    id: severity
    attributes:
      label: Impact
      description: How serious is this issue?
      options:
        - "🔴 Critical — guidance could lead to a real security or safety problem"
        - "🟠 High — guidance is clearly wrong and could mislead practitioners"
        - "🟡 Medium — guidance is incomplete or could be more accurate"
        - "🟢 Low — minor wording issue or typo"
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Before Submitting
      options:
        - label: I searched existing issues and this hasn't been reported yet
          required: true
        - label: I have identified the specific file and line where the issue occurs
          required: true
